# Generated by Django 5.2.14 on 2026-05-31 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="题目标题"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="URL别名"
                    ),
                ),
                ("description", models.TextField(verbose_name="题目描述")),
                ("input_description", models.TextField(verbose_name="输入描述")),
                ("output_description", models.TextField(verbose_name="输出描述")),
                ("sample_input", models.TextField(verbose_name="示例输入")),
                ("sample_output", models.TextField(verbose_name="示例输出")),
                ("hint", models.TextField(blank=True, null=True, verbose_name="提示")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "简单"),
                            ("Medium", "中等"),
                            ("Hard", "困难"),
                        ],
                        default="Medium",
                        max_length=10,
                        verbose_name="难度",
                    ),
                ),
                (
                    "time_limit",
                    models.IntegerField(default=2000, verbose_name="时间限制(毫秒)"),
                ),
                (
                    "memory_limit",
                    models.IntegerField(default=256, verbose_name="内存限制(MB)"),
                ),
                (
                    "total_submissions",
                    models.IntegerField(default=0, verbose_name="总提交数"),
                ),
                (
                    "accepted_submissions",
                    models.IntegerField(default=0, verbose_name="通过数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="是否公开"),
                ),
            ],
            options={
                "verbose_name": "题目",
                "verbose_name_plural": "题目列表",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_data", models.TextField(verbose_name="输入数据")),
                ("expected_output", models.TextField(verbose_name="预期输出")),
                (
                    "is_sample",
                    models.BooleanField(default=False, verbose_name="是否为示例"),
                ),
                ("score", models.IntegerField(default=10, verbose_name="分值")),
                ("order", models.IntegerField(default=0, verbose_name="执行顺序")),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="oj_problems.problem",
                        verbose_name="所属题目",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试用例",
                "verbose_name_plural": "测试用例列表",
                "ordering": ["order"],
            },
        ),
    ]
