# Generated by Django 5.2.14 on 2026-05-31 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("oj_problems", "0001_initial"),
        ("oj_submissions", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JudgeStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="日期")),
                (
                    "total_submissions",
                    models.IntegerField(default=0, verbose_name="总提交数"),
                ),
                (
                    "accepted_submissions",
                    models.IntegerField(default=0, verbose_name="通过数"),
                ),
                (
                    "average_execution_time",
                    models.IntegerField(default=0, verbose_name="平均执行时间(ms)"),
                ),
                (
                    "average_score",
                    models.IntegerField(default=0, verbose_name="平均得分"),
                ),
                (
                    "language_stats",
                    models.JSONField(default=dict, verbose_name="语言统计"),
                ),
                (
                    "difficulty_stats",
                    models.JSONField(default=dict, verbose_name="难度统计"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "判题统计",
                "verbose_name_plural": "判题统计列表",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="JudgeTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "等待判题"),
                            ("Judging", "正在判题"),
                            ("Accepted", "答案正确"),
                            ("Wrong Answer", "答案错误"),
                            ("Time Limit Exceeded", "超时"),
                            ("Memory Limit Exceeded", "内存超限"),
                            ("Runtime Error", "运行时错误"),
                            ("Compile Error", "编译错误"),
                            ("System Error", "系统错误"),
                        ],
                        default="Pending",
                        max_length=30,
                        verbose_name="判题状态",
                    ),
                ),
                ("total_score", models.IntegerField(default=0, verbose_name="总得分")),
                ("max_score", models.IntegerField(default=0, verbose_name="最高分")),
                (
                    "total_execution_time",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="总执行时间(ms)"
                    ),
                ),
                (
                    "max_execution_time",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="最大执行时间(ms)"
                    ),
                ),
                (
                    "min_execution_time",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="最小执行时间(ms)"
                    ),
                ),
                (
                    "total_execution_memory",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="总内存占用(KB)"
                    ),
                ),
                (
                    "max_execution_memory",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="最大内存占用(KB)"
                    ),
                ),
                (
                    "passed_test_cases",
                    models.IntegerField(default=0, verbose_name="通过的测试用例数"),
                ),
                (
                    "total_test_cases",
                    models.IntegerField(default=0, verbose_name="总测试用例数"),
                ),
                (
                    "result_details",
                    models.JSONField(blank=True, default=dict, verbose_name="详细结果"),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="优先级")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="重试次数"),
                ),
                (
                    "max_retries",
                    models.IntegerField(default=3, verbose_name="最大重试次数"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "judge_server",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="判题服务器"
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judge_task",
                        to="oj_submissions.submission",
                        verbose_name="提交记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "判题任务",
                "verbose_name_plural": "判题任务列表",
                "ordering": ["-priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestCaseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "等待判题"),
                            ("Judging", "正在判题"),
                            ("Accepted", "答案正确"),
                            ("Wrong Answer", "答案错误"),
                            ("Time Limit Exceeded", "超时"),
                            ("Memory Limit Exceeded", "内存超限"),
                            ("Runtime Error", "运行时错误"),
                            ("Compile Error", "编译错误"),
                            ("System Error", "系统错误"),
                        ],
                        default="Pending",
                        max_length=30,
                        verbose_name="状态",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("Passed", "通过"),
                            ("Failed", "失败"),
                            ("Partial", "部分通过"),
                        ],
                        default="Failed",
                        max_length=20,
                        verbose_name="结果",
                    ),
                ),
                ("score", models.IntegerField(default=0, verbose_name="得分")),
                (
                    "execution_time",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="执行时间(ms)"
                    ),
                ),
                (
                    "execution_memory",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="内存占用(KB)"
                    ),
                ),
                (
                    "expected_output",
                    models.TextField(blank=True, verbose_name="预期输出"),
                ),
                (
                    "actual_output",
                    models.TextField(blank=True, verbose_name="实际输出"),
                ),
                ("input_data", models.TextField(blank=True, verbose_name="输入数据")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "is_sample",
                    models.BooleanField(default=False, verbose_name="是否为示例"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="顺序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "judge_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="oj_judge.judgetask",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oj_problems.testcase",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试用例结果",
                "verbose_name_plural": "测试用例结果列表",
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="judgetask",
            index=models.Index(
                fields=["status", "created_at"], name="oj_judge_ju_status_5b41f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="judgetask",
            index=models.Index(
                fields=["submission"], name="oj_judge_ju_submiss_9854db_idx"
            ),
        ),
    ]
