# Generated by Django 5.2.14 on 2026-05-31 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("oj_problems", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "等待判题"),
                            ("Judging", "正在判题"),
                            ("Accepted", "答案正确"),
                            ("Wrong Answer", "答案错误"),
                            ("Time Limit Exceeded", "超时"),
                            ("Memory Limit Exceeded", "内存超限"),
                            ("Runtime Error", "运行时错误"),
                            ("Compile Error", "编译错误"),
                            ("System Error", "系统错误"),
                        ],
                        default="Pending",
                        max_length=30,
                        verbose_name="状态",
                    ),
                ),
                (
                    "actual_output",
                    models.TextField(blank=True, verbose_name="实际输出"),
                ),
                (
                    "execution_time",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="运行时间(ms)"
                    ),
                ),
                (
                    "execution_memory",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="内存占用(KB)"
                    ),
                ),
                (
                    "is_passed",
                    models.BooleanField(default=False, verbose_name="是否通过"),
                ),
            ],
            options={
                "verbose_name": "测试结果",
                "verbose_name_plural": "测试结果列表",
                "ordering": ["test_case__order"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(verbose_name="代码内容")),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python 3"),
                            ("java", "Java"),
                            ("cpp", "C++"),
                            ("c", "C"),
                            ("javascript", "JavaScript"),
                            ("go", "Go"),
                            ("rust", "Rust"),
                        ],
                        default="python",
                        max_length=20,
                        verbose_name="编程语言",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "等待判题"),
                            ("Judging", "正在判题"),
                            ("Accepted", "答案正确"),
                            ("Wrong Answer", "答案错误"),
                            ("Time Limit Exceeded", "超时"),
                            ("Memory Limit Exceeded", "内存超限"),
                            ("Runtime Error", "运行时错误"),
                            ("Compile Error", "编译错误"),
                            ("System Error", "系统错误"),
                        ],
                        default="Pending",
                        max_length=30,
                        verbose_name="判题状态",
                    ),
                ),
                (
                    "execution_time",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="运行时间(ms)"
                    ),
                ),
                (
                    "execution_memory",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="内存占用(KB)"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                ("score", models.IntegerField(default=0, verbose_name="得分")),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "judged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="判题完成时间"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="是否公开"),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="oj_problems.problem",
                        verbose_name="所属题目",
                    ),
                ),
            ],
            options={
                "verbose_name": "提交记录",
                "verbose_name_plural": "提交记录列表",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
