# Generated by Django 5.2.14 on 2026-05-31 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("oj_problems", "0001_initial"),
        ("oj_submissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="提交用户",
            ),
        ),
        migrations.AddField(
            model_name="submissiontestresult",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_results",
                to="oj_submissions.submission",
                verbose_name="所属提交",
            ),
        ),
        migrations.AddField(
            model_name="submissiontestresult",
            name="test_case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="oj_problems.testcase",
                verbose_name="测试用例",
            ),
        ),
    ]
